name: Testing

on: [push]

jobs:
  unit-test:
    name: Unit testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('composer.lock') }}

      - name: Installing dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 8.2
          php_extensions: "json zip sodium pcntl bcmath"

      - name: Running unit test
        uses: php-actions/phpunit@v3
        with:
          version: 10.5.13
          php_version: 8.2
          php_extensions: "json zip sodium pcntl bcmath xdebug pcov"
          args: "-d date.timezone=Asia/Jakarta"
          memory_limit: 300M
          configuration: phpunit.xml
          coverage_clover: "./coverage/clover.xml"

      - name: Ensure coverage > 55
        id: test-coverage
        uses: johanvanhelden/gha-clover-test-coverage-check@v1
        with:
          percentage: "55"
          filename: "./coverage/clover.xml"
